// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZYSJModer.Moder;

namespace ZYSJModer.Migrations
{
    [DbContext(typeof(TodoContextModelSnapshot))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZYSJModer.Moder.BOOKS", b =>
                {
                    b.Property<Guid>("BID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BJJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BID");

                    b.ToTable("BOOKS");
                });

            modelBuilder.Entity("ZYSJModer.Moder.CSXX", b =>
                {
                    b.Property<Guid>("XSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("XSDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("XSIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("XSWJ")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("XSXX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XSID");

                    b.ToTable("CSXX");
                });

            modelBuilder.Entity("ZYSJModer.Moder.Dictionary", b =>
                {
                    b.Property<Guid>("ZDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZDNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZDTYPE")
                        .HasColumnType("int");

                    b.HasKey("ZDID");

                    b.ToTable("Dictionary");
                });

            modelBuilder.Entity("ZYSJModer.Moder.FILE", b =>
                {
                    b.Property<Guid>("FID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("FNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FUSER")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FID");

                    b.ToTable("FILE");
                });

            modelBuilder.Entity("ZYSJModer.Moder.HFXX", b =>
                {
                    b.Property<Guid>("HFID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DZNUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("HFDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("HFPL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HFUSER")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HFID");

                    b.ToTable("HFXX");
                });

            modelBuilder.Entity("ZYSJModer.Moder.JDXX", b =>
                {
                    b.Property<Guid>("JDID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CSID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JDING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JDNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JDWJ")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JDID");

                    b.ToTable("JDXX");
                });

            modelBuilder.Entity("ZYSJModer.Moder.JL", b =>
                {
                    b.Property<Guid>("JID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DZNUM")
                        .HasColumnType("int");

                    b.Property<string>("JLIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JLXX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JTITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JID");

                    b.ToTable("JL");
                });

            modelBuilder.Entity("ZYSJModer.Moder.LY", b =>
                {
                    b.Property<Guid>("LID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LYRQ")
                        .HasColumnType("datetime2");

                    b.Property<string>("LYUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LYXX")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LID");

                    b.ToTable("LY");
                });

            modelBuilder.Entity("ZYSJModer.Moder.PLXX", b =>
                {
                    b.Property<Guid>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DZNUM")
                        .HasColumnType("int");

                    b.Property<DateTime>("PDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("PL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PLHFID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PUSER")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PID");

                    b.ToTable("PLXX");
                });

            modelBuilder.Entity("ZYSJModer.Moder.Uselogin", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LV")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PWD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Users")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("Uselogin");
                });

            modelBuilder.Entity("ZYSJModer.Moder.Users", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BIRTHDAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("BZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DSF")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NICK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QQID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPECIAALIZED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STATE")
                        .HasColumnType("int");

                    b.Property<string>("UIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UQM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORKPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZYM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZYSJModer.Moder.VIDES", b =>
                {
                    b.Property<Guid>("VID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VSC")
                        .HasColumnType("int");

                    b.HasKey("VID");

                    b.ToTable("VIDES");
                });
#pragma warning restore 612, 618
        }
    }
}
